# Generated by Django 5.1.5 on 2025-02-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verificationtoken'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['token'], name='accounts_ve_token_e31831_idx'),
        ),
    ]
