# Generated by Django 5.1.6 on 2025-02-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verificationtoken_accounts_ve_token_e31831_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='VerificationToken',
        ),
    ]
