services:
  redis: 
    container_name: channel_layer
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

  django:
    container_name: web
    build: 
      context: .
      dockerfile: Backend/Dockerfile
    command: python manage.py runserver
    volumes:
      - ./Backend:/app
    ports:
      - 8000:8000
    depends_on:
      - redis