# Generated by Django 5.1.6 on 2025-02-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Room',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='chat_room_name_8fdd04_idx',
            old_name='chat_group_name_c665ce_idx',
        ),
    ]
